language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
env:
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
  - FEDORA_VERSION="3.8.1"
# broken right now, should be fixed.
#  - FEDORA_VERSION="3.5"
before_script:
  - mysql -u root -e "create database fedora;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fedora.* To 'fedora'@'localhost' IDENTIFIED BY 'fedora';"
  - wget http://alpha.library.yorku.ca/islandora_tomcat.$FEDORA_VERSION.tar.gz
  - tar -xzvf islandora_tomcat.$FEDORA_VERSION.tar.gz
  - cd islandora_tomcat
  - pwd
  - export CATALINA_HOME='.'
  - export JAVA_OPTS="-Xms1024m -Xmx1024m -XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -Djavax.net.ssl.trustStore=$CATALINA_HOME/fedora/server/truststore -Djavax.net.ssl.trustStorePassword=tomcat"
  - ./bin/startup.sh
  - cd ..
  - sleep 10
script:
  - phpunit -c tests/travis.xml tests/
after_failure:
  - cat /home/travis/build/ruebot/tuque/islandora_tomcat/fedora/server/logs/fedora.log
#notifications:
#  irc: "irc.freenode.org#islandora"
